language: php

php:
  - 7.4
  - 8.0
  - 8.1

matrix:
  include:
    - php: 8.1
      env: LARAVEL_VERSION=10.*
    - php: 8.1
      env: LARAVEL_VERSION=9.*
    - php: 8.1
      env: LARAVEL_VERSION=8.*
    - php: 8.0
      env: LARAVEL_VERSION=7.*
    - php: 7.4
      env: LARAVEL_VERSION=6.*
    - php: 7.4
      env: LARAVEL_VERSION=5.6.*

before_install:
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update
  
install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
